<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<!--page generated by WebAcappella-->
<!-- 2015-02-21T18:13:11 ******************************-->
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7;IE=EmulateIE9" />
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<meta name="generator" content="WebAcappella 4.6.5  ecommerce (WIN) #5d45"/>
<title>Sistema de Login - Web Acappella</title>
<meta name="keywords" content=""/>
<meta name="description" content=""/>

<style type="text/css">
body{margin-left:0px;margin-top:0px;margin-right:0px;margin-bottom:0px;background-image:url('topo.png');background-repeat: repeat-x;background-color:#ffffff;}
</style>
<link rel="stylesheet" type="text/css" href="wa_global_style.css"/>
<script type="text/javascript"  src="jquery.js?v=86c"></script>
<script type="text/javascript">
var waJSQuery = jQuery.noConflict();
</script>
<script type="text/javascript"  src="webacappella_core.js?v=1ups"></script>
<!--[if lte IE 8]><script type="text/javascript"  src="excanvas.js?v=1f2a"></script>
<![endif]-->
<!--[if lte IE 8]><script type="text/javascript"  src="webacappella_patch_ie8.js?v=tc5"></script>
<![endif]-->
<script type="text/javascript">
document.write("\u003cscript type='text/javascript'  src='wa_site_global_settings.js?v=1rlo3gjf9192kx"+urlSuffixe(1)+"'>\u003c/script>");
</script>
<script type="text/javascript"  src="jquery.mousewheel.js?v=use"></script>
<link href="webacappella.css?v=10nl" rel="stylesheet" type="text/css" media="all"/>
<!--[if lte IE 7]>
<link href="webacappella_ie.css?v=1tjn" rel="stylesheet" type="text/css" media="all"/>
<![endif]-->
<script type="text/javascript"  src="webacappella_tools.js?v=blf"></script>

<!-- ********* CUSTOM PAGE HEAD CODE (start) *******-->
<link rel="stylesheet" href="css/demo.css">
<link rel="stylesheet" href="css/sky-forms.css">
<!-- ********* CUSTOM PAGE HEAD CODE (end)   *******-->

<script type="text/javascript">
waJSQuery(function() {
initializeWA_JQuery()
});
</script>
<link href='//fonts.googleapis.com/css?family=Oswald:300&amp;text=JoLMr%C3%A1NsOuR%C3%81S%2FTU%3AadeAChDiE%20GmIn' rel="stylesheet" type="text/css" />
<script type="text/javascript">
var waWebFontDescription={families:[
"Oswald"]}
</script>

</head>
<body><div id='wa-dialog-container' class='wa-fullscreen-contenair' style='position:absolute;z-index:52000;'></div><div id='html-centered' style='position:relative;width:100%;z-index:200;'><div id='is-global-layer' class='wa-main-page-contenair'  style='position:relative;z-index:200;top:0px;width:1000px;;text-align:left;margin:0 auto; '><div style="position:absolute;top:1px;left:0px;width:1px;height:1px;"><a name="anchor-top">&nbsp;</a></div>
<span style="position:absolute;z-index:10012;left:999px;top:671px;width:1px;height:1px;-moz-border-radius:0px;border-radius:0px;-webkit-border-radius:0px;border:0px;background:-webkit-gradient(linear,0 0, 0 1,from(#5ba1f9),to(#226fdb));background:-moz-linear-gradient(top left 270deg,#5ba1f9 0px,#226fdb 1px);" class="wa-bg-gradient param[grad(0 0 0 1 #5ba1f9 #226fdb) border(0 #969696)] wa-comp "></span><div class="wa-comp" style="position:absolute;z-index:10008;left:395px;top:737px;width:209px;height:100px;border:0px;background:rgba(0,0,0,0);" ><img src='wa_5w6g5siewv16w7_text.png?v=46o9q05e8idh3rs' style="border:0px;position:absolute;z-index:10;top: 0px; left: 0px; width: 209px; height: 100px;" title="" alt="" /></div><div class="wa-comp" style="position:absolute;z-index:10004;left:250px;top:207px;width:500px;height:500px;">

<!-- ********* CUSTOM HTML CODE (start) *******-->
<form action="validacao.php" method="post" class="sky-form">
				<header>Login</header>
				
				<fieldset>					
					<section>
						<div class="row">
							<label  class="label col col-4">Usuário</label>
							<div class="col col-8">
								<label class="input">
									<i class="icon-append icon-user"></i>
									<input name="usuario" type="text">
									
								</label>
							</div>
						</div>
					</section>
					
					<section>
						<div class="row">
							<label  class="label col col-4">Senha</label>
							<div class="col col-8">
								<label class="input">
									<i class="icon-append icon-lock"></i>
									<input name="senha" type="password">
								</label>
								<div class="note"><a href="recupera.php">Esqueceu a Senha?</a></div>
							</div>
						</div>
					</section>
					
					<section>
						<div class="row">
							<div class="col col-4"></div>
							<div class="col col-8">
								<label class="checkbox"><input type="checkbox" name="checkbox-inline" checked><i></i>Ficar Logado</label>
							</div>
						</div>
					</section>
				</fieldset>
				<footer>
					<button type="submit" class="button">Log in</button>
					<a href="registro.php" class="button button-secondary">Registrar</a>
				</footer>
			</form>
<!-- ********* CUSTOM HTML CODE (end) *******-->

</div><span style="position:absolute;z-index:10000;left:999px;top:615px;width:1px;height:1px;-moz-border-radius:0px;border-radius:0px;-webkit-border-radius:0px;border:0px;background:-webkit-gradient(linear,0 0, 0 1,from(#5ba1f9),to(#226fdb));background:-moz-linear-gradient(top left 270deg,#5ba1f9 0px,#226fdb 1px);" class="wa-bg-gradient param[grad(0 0 0 1 #5ba1f9 #226fdb) border(0 #969696)] wa-comp "></span><img src="key-white.png?v=42pvug5e8id8zgs" alt=""  class="wa-img wa-comp " style="position:absolute;z-index:16;left:342px;top:21px;width:60px;height:60px;border:0px;"/><div style="position:absolute;z-index:4;left:0px;top:149px;width:1000px;height:60px;border:0px;background:rgba(0,0,0,0);overflow:hidden;" class="wa-comp wa-text wa-bg-gradient param[grad(rgba(0,0,0,0)) border(0 #969696)]  " ><div style="position:absolute;z-index:10;line-height:1.2;margin:2px;top:0px;left:0px;width:998px;height:58px;word-wrap:break-word;overflow-y:auto;overflow-x:hidden;" ><div align="center"><span style="font-family:'Oswald';font-size:17px;font-weight:300;color:#3d3d3d;" >RESTRINJA ACESSOS A ALGUMAS &#193;REAS DO SEU SITE</span></div></div></div><div style="position:absolute;z-index:0;left:169px;top:23px;width:715px;height:100px;border:0px;background:rgba(0,0,0,0);overflow:hidden;" class="wa-comp wa-text wa-bg-gradient param[grad(rgba(0,0,0,0)) border(0 #969696)]  " ><div style="position:absolute;z-index:10;line-height:1.2;margin:2px;top:0px;left:0px;width:713px;height:98px;word-wrap:break-word;overflow-y:auto;overflow-x:hidden;" ><div align="center"><span style="font-family:'Oswald';font-size:36px;font-weight:300;color:#ffffff;" >SISTEMA DE LOGIN</span></div></div></div><div style="position:absolute;top:816px;left:0px;width:1px;height:1px;" ><a name="anchor-bottom">&nbsp;</a></div>
<div id='dynmenu-container' style='position:absolute;z-index:51000;'></div></div>
</div>  <!--end html-centered-->
<script type="text/javascript">
<!--
document.webaca_page_option_background=0
document.webaca_page_background_img_size=[200,100]
document.webaca_page_is_centered=true;
document.webaca_width_page=1000;
document.webaca_height_page=836;
document.webaca_banner_height=0;
document.webaca_is_preview=false;
var wa_global_market = {markets:new Array(),id_modif_dlg_js:''};
Translator.m_lang="pt";
Translator.m_languages={}
Translator.m_lang_for_filename="";
function wa_timeout(_fct,_time,p1,p2,p3){return setTimeout(_fct,_time,p1,p2,p3)}
function wa_evaluate(_s){return eval(_s)}
function IS_onload(){
IS_onload_WA();
}
-->
</script>
<script type="text/javascript" src='wa_common_messages_pt.js?v='></script>
<script type="text/javascript">
<!--
WA_loadMessages();
-->
</script>
<script type="text/javascript">
<!--
-->
</script>
</body>
</html>

